### ISSUE TITLE
Breaks under concurrency when using gevent

### ISSUE THREAD

**Issue by ddorian** [pallets-eco/flask-sqlalchemy-lite#11]
When running concurrent requests to the flask app I get this error often. It goes away if I comment this line:
[`app.teardown_appcontext(_close_async_sessions)`.](https://github.com/pallets-eco/flask-sqlalchemy-lite/blob/0bf189cfd6a8246862686e4f8d34c954d6cf888b/src/flask_sqlalchemy_lite/_extension.py#L83)

```python
Debugging middleware caught exception in streamed response at a point where response headers were already sent.
Traceback (most recent call last):
  File "/home/user/proj/.venv/lib/python3.12/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/proj/.venv/lib/python3.12/site-packages/whitenoise/base.py", line 81, in __call__
    return self.application(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/proj/.venv/lib/python3.12/site-packages/werkzeug/middleware/proxy_fix.py", line 183, in __call__
    return self.app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/proj/.venv/lib/python3.12/site-packages/opentelemetry/instrumentation/flask/__init__.py", line 390, in _wrapped_app
    result = wsgi_app(wrapped_app_environ, _start_response)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/proj/.venv/lib/python3.12/site-packages/flask/app.py", line 1489, in wsgi_app
    ctx.pop(error)
  File "/home/user/proj/.venv/lib/python3.12/site-packages/flask/ctx.py", line 426, in pop
    app_ctx.pop(exc)
  File "/home/user/proj/.venv/lib/python3.12/site-packages/flask/ctx.py", line 262, in pop
    self.app.do_teardown_appcontext(exc)
  File "/home/user/proj/.venv/lib/python3.12/site-packages/flask/app.py", line 1344, in do_teardown_appcontext
    self.ensure_sync(func)(exc)
RuntimeError: You cannot use AsyncToSync in the same thread as an async event loop - just await the async function directly.
```

**Comment by davidism** [comment]
I think this needs to be reported to asgiref, and note that there are existing issues where gevent compatibility is an issue: https://github.com/django/asgiref/issues?q=gevent There's nothing Flask-SQLAlchemy-Lite is doing here besides normal registration of callbacks, and Flask is doing its normal use of asgiref to accomplish that with async callbacks.
